-- CREATE TABLE, query das criaçõs das tabelas
CREATE TABLE DEPARTAMENTO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE TECNICO (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	STATUS VARCHAR(100) DEFAULT 'Disponivel'
)
CREATE TABLE COLABORADOR (
	MATRICULA VARCHAR(100) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	STATUS VARCHAR(100) DEFAULT 'Disponivel',
	ID_DEPARTAMENTO INTEGER NOT NULL,
	CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID)
);

CREATE TABLE DISPOSITIVO (
	ID SERIAL PRIMARY KEY,
	MARCA VARCHAR(100),
	DATA_COMPRA DATE,
	STATUS VARCHAR(100) DEFAULT 'Disponivel',
	ID_COLABORADOR VARCHAR(100) UNIQUE NOT NULL,
	CONSTRAINT FK_COLABORADOR FOREIGN KEY (ID_COLABORADOR) REFERENCES COLABORADOR (MATRICULA)
);

CREATE TABLE CHAMADOS (
	ID SERIAL PRIMARY KEY,
	PROBLEMA_REPORTADO TEXT NOT NULL,
	STATUS_DO_CHAMADO VARCHAR(100) DEFAULT 'Aberto',
	DATA_ENTRADA TIMESTAMPTZ DEFAULT NOW(),
	DATA_FINALIZAÇÃO TIMESTAMPTZ,
	ID_DISPOSITIVO INTEGER,
	ID_TECNICO INTEGER,
	ID_COLABORADOR_ABRIU VARCHAR(20) NOT NULL,
	CONSTRAINT FK_DISPOSITIVO FOREIGN KEY (ID_DISPOSITIVO) REFERENCES DISPOSITIVO (ID),
	CONSTRAINT FK_TECNICO FOREIGN KEY (ID_TECNICO) REFERENCES TECNICO (ID),
	CONSTRAINT FK_COLABORADOR FOREIGN KEY (ID_COLABORADOR_ABRIU) REFERENCES COLABORADOR (MATRICULA)
);

-- Criando uma tebala nova
CREATE TABLE HISTORICO_DE_COLABORADOR (
	ID SERIAL PRIMARY KEY,
	ID_COLABORADOR VARCHAR(20) NOT NULL,
	ID_DISPOSITIVO INTEGER,
	STATUS VARCHAR(100),
	DATA_INICIO DATE,
	DATA_FINAL DATE,
	CONSTRAINT FK_COLABORADOR FOREIGN KEY (ID_COLABORADOR) REFERENCES COLABORADOR (MATRICULA),
	CONSTRAINT FK_DISPOSITIVO FOREIGN KEY (ID_DISPOSITIVO) REFERENCES DISPOSITIVO (ID)
);
