-- Teste Select 
SELECT
	*
FROM
	COLABORADOR;

SELECT
	*
FROM
	DEPARTAMENTO;

SELECT
	*
FROM
	DISPOSITIVO;

SELECT
	*
FROM
	TECNICO;

SELECT
	*
FROM
	HISTORICO_DE_COLABORADOR;

SELECT
	*
FROM
	CHAMADOS;

SELECT
	NOME,
	MARCA,
	DISPOSITIVO.STATUS
FROM
	COLABORADOR
	JOIN DISPOSITIVO ON COLABORADOR.MATRICULA = DISPOSITIVO.ID_COLABORADOR;

SELECT
	MATRICULA,
	COLABORADOR.NOME AS "colaborador nome",
	DEPARTAMENTO.NOME AS "departamento nome",
	STATUS
FROM
	COLABORADOR
	JOIN DEPARTAMENTO ON COLABORADOR.ID_DEPARTAMENTO = DEPARTAMENTO.ID;

SELECT
	ID,
	MARCA,
	DATA_COMPRA,
	COLABORADOR.NOME
FROM
	DISPOSITIVO
	JOIN COLABORADOR ON DISPOSITIVO.ID_COLABORADOR = COLABORADOR.MATRICULA;

SELECT
	MARCA,
	COLABORADOR.NOME,
	DEPARTAMENTO.NOME AS "departamento"
FROM
	DISPOSITIVO
	JOIN COLABORADOR ON DISPOSITIVO.ID_COLABORADOR = COLABORADOR.MATRICULA
	JOIN DEPARTAMENTO ON COLABORADOR.ID_DEPARTAMENTO = DEPARTAMENTO.ID;

SELECT
	COLABORADOR.NOME,
	MARCA,
	HISTORICO_DE_COLABORADOR.DATA_INICIO
FROM
	HISTORICO_DE_COLABORADOR
	JOIN COLABORADOR ON HISTORICO_DE_COLABORADOR.ID_COLABORADOR = COLABORADOR.MATRICULA
	JOIN DISPOSITIVO ON HISTORICO_DE_COLABORADOR.ID_DISPOSITIVO = DISPOSITIVO.ID;